services:
  - type: web
    name: monetacore
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /livez
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MONETACORE_ConnectionStrings__DefaultConnection
        sync: false
      - key: MONETACORE_PayMongo__SecretKey
        sync: false
